export interface ToolDefinition {
  id: string;
  name: string;
  category: "osint" | "downloader" | "ai" | "files" | "monitor" | "workspace";
  categoryLabel: string;
  description: string;
  endpoint: string;
  badge?: string;
  iconName: string;
  requiresKey: boolean;
  requiredProviderName?: string;
  isLegalNoticeRequired?: boolean;
}

export const TOOLS_CATALOG: ToolDefinition[] = [
  // 1-6 Public Media Downloaders
  {
    id: "tiktok-downloader",
    name: "TikTok Downloader",
    category: "downloader",
    categoryLabel: "Media Downloader",
    description: "Unduh video TikTok publik milik pengguna atau berizin dengan metadata resolusi dan durasi.",
    endpoint: "/api/media/download",
    iconName: "Video",
    requiresKey: false,
    badge: "ENGINE AKTIF",
    requiredProviderName: "TikWM Live Engine (Built-in)",
  },
  {
    id: "instagram-downloader",
    name: "Instagram Downloader",
    category: "downloader",
    categoryLabel: "Media Downloader",
    description: "Preview dan unduh foto, video reels publik tanpa mengakses akun privat via OpenGraph & Microlink Resolver.",
    endpoint: "/api/media/download",
    iconName: "Instagram",
    requiresKey: false,
    badge: "ENGINE AKTIF",
    requiredProviderName: "Microlink / Cobalt Hub",
  },
  {
    id: "youtube-downloader",
    name: "YouTube Downloader",
    category: "downloader",
    categoryLabel: "Media Downloader",
    description: "Preview metadata resmi dan unduh audio/video konten publik yang berizin via YouTube oEmbed stream adapter.",
    endpoint: "/api/media/download",
    iconName: "Youtube",
    requiresKey: false,
    badge: "ENGINE AKTIF",
    requiredProviderName: "YouTube oEmbed / Stream Adapter",
    isLegalNoticeRequired: true,
  },
  {
    id: "twitter-downloader",
    name: "X/Twitter Downloader",
    category: "downloader",
    categoryLabel: "Media Downloader",
    description: "Ambil media resolusi tinggi dan video dari postingan publik X/Twitter melalui FxTwitter Syndication Engine.",
    endpoint: "/api/media/download",
    iconName: "Twitter",
    requiresKey: false,
    badge: "ENGINE AKTIF",
    requiredProviderName: "FxTwitter Syndication Engine",
  },
  {
    id: "facebook-downloader",
    name: "Facebook Downloader",
    category: "downloader",
    categoryLabel: "Media Downloader",
    description: "Unduh video publik Facebook tanpa bypass login atau proteksi privat via public media stream extractor.",
    endpoint: "/api/media/download",
    iconName: "Film",
    requiresKey: false,
    badge: "ENGINE AKTIF",
    requiredProviderName: "Public Stream Extractor",
  },
  {
    id: "pinterest-downloader",
    name: "Pinterest Downloader",
    category: "downloader",
    categoryLabel: "Media Downloader",
    description: "Ekstrak gambar dan video resolusi asli dari pin publik Pinterest menggunakan metadata engine.",
    endpoint: "/api/media/download",
    iconName: "Image",
    requiresKey: false,
    badge: "ENGINE AKTIF",
    requiredProviderName: "Pinterest Public Metadata Engine",
  },

  // 7-11 Social & Public Search Intelligence
  {
    id: "social-profile-analyzer",
    name: "Social Profile Analyzer",
    category: "osint",
    categoryLabel: "Social OSINT",
    description: "Analisis metadata profil publik di berbagai platform: bio, tautan, verifikasi, dan follower publik.",
    endpoint: "/api/osint/profile",
    iconName: "UserCheck",
    requiresKey: false,
    badge: "POPULER",
  },
  {
    id: "username-checker",
    name: "Username Checker",
    category: "osint",
    categoryLabel: "Social OSINT",
    description: "Pemeriksaan ketersediaan username di 20+ platform publik terpopuler secara simultan.",
    endpoint: "/api/osint/username",
    iconName: "AtSign",
    requiresKey: false,
    badge: "REAL-TIME",
  },
  {
    id: "social-media-search",
    name: "Social Media Search",
    category: "osint",
    categoryLabel: "Social OSINT",
    description: "Cari postingan publik berbasis keyword dengan filter tanggal, bahasa, dan platform.",
    endpoint: "/api/osint/social-search",
    iconName: "Search",
    requiresKey: false,
  },
  {
    id: "hashtag-analyzer",
    name: "Hashtag Analyzer",
    category: "osint",
    categoryLabel: "Social OSINT",
    description: "Analisis statistik tren hashtag, engagement publik, dan frekuensi penyebaran.",
    endpoint: "/api/osint/hashtag",
    iconName: "Hash",
    requiresKey: false,
  },
  {
    id: "keyword-monitor",
    name: "Keyword Monitor",
    category: "monitor",
    categoryLabel: "Monitoring",
    description: "Pemantauan kata kunci otomatis berbasis feed RSS/publik dengan sistem notifikasi insiden.",
    endpoint: "/api/monitors",
    iconName: "Radio",
    requiresKey: false,
  },

  // 12-19 Network & Web Intelligence
  {
    id: "domain-intelligence",
    name: "Domain Intelligence",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Intelijen domain lengkap: Registrar, usia domain, nameservers, SSL, dan pemetaan ASN.",
    endpoint: "/api/osint/domain",
    iconName: "Globe",
    requiresKey: false,
    badge: "LENGKAP",
  },
  {
    id: "whois-lookup",
    name: "WHOIS Lookup",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Query langsung via raw socket port 43 ke server WHOIS resmi IANA dan TLD dengan penanganan privasi.",
    endpoint: "/api/osint/whois",
    iconName: "FileSearch",
    requiresKey: false,
  },
  {
    id: "dns-lookup",
    name: "DNS Lookup",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Resolusi mendalam DNS records: A, AAAA, MX, TXT, NS, CNAME, SOA, CAA, PTR dengan TTL asli.",
    endpoint: "/api/osint/dns",
    iconName: "Server",
    requiresKey: false,
  },
  {
    id: "ip-lookup",
    name: "IP Address Lookup",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Geolokasi level kota/wilayah, ASN, ISP, timezone, dan reverse DNS (anti-doxxing: tanpa alamat privat).",
    endpoint: "/api/osint/ip",
    iconName: "Compass",
    requiresKey: false,
  },
  {
    id: "url-scanner",
    name: "URL Security Scanner",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Audit status HTTP, redirect chains, sertifikat SSL, latensi, security headers & proteksi anti-SSRF.",
    endpoint: "/api/osint/url",
    iconName: "ShieldAlert",
    requiresKey: false,
    badge: "SSRF-GUARD",
  },
  {
    id: "tech-detector",
    name: "Website Technology Detector",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Deteksi pasif CMS, Framework (React, Next, Vue), CDN, server, analytics tanpa injeksi kode.",
    endpoint: "/api/osint/technology",
    iconName: "Layers",
    requiresKey: false,
  },
  {
    id: "website-screenshot",
    name: "Website Screenshot Sandbox",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Tangkapan layar halaman web publik dalam environment sandbox aman dengan blokir private IP SSRF Guard.",
    endpoint: "/api/osint/screenshot",
    iconName: "Camera",
    requiresKey: false,
    badge: "SANDBOX AKTIF",
    requiredProviderName: "WordPress mshots & Cloud Render",
  },
  {
    id: "link-extractor",
    name: "Link Extractor",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Ekstrak semua hyperlink sebuah halaman publik dan kelompokkan menjadi Internal vs External.",
    endpoint: "/api/osint/links",
    iconName: "ExternalLink",
    requiresKey: false,
  },

  // 20-21 Validator
  {
    id: "email-validator",
    name: "Email Validator",
    category: "osint",
    categoryLabel: "Utility",
    description: "Validasi sintaks RFC 5322, verifikasi DNS MX, dan deteksi 500+ penyedia disposable email.",
    endpoint: "/api/tools/validate-email",
    iconName: "MailCheck",
    requiresKey: false,
  },
  {
    id: "phone-validator",
    name: "Phone Number Validator",
    category: "osint",
    categoryLabel: "Utility",
    description: "Validasi standar Google libphonenumber, deteksi negara, tipe nomor (Mobile/Fixed/VoIP) & operator umum.",
    endpoint: "/api/tools/validate-phone",
    iconName: "PhoneCall",
    requiresKey: false,
  },

  // 22-27 AI & Threat Intelligence Analysis
  {
    id: "text-summarizer",
    name: "Text Summarizer",
    category: "ai",
    categoryLabel: "AI Intelligence",
    description: "Ringkas dokumen atau artikel panjang dalam Bahasa Indonesia & Inggris dengan estimasi token.",
    endpoint: "/api/ai/summarize",
    iconName: "FileText",
    requiresKey: false, // Dual engine: native extractive NLP works out of the box!
  },
  {
    id: "keyword-extractor",
    name: "Keyword Extractor",
    category: "ai",
    categoryLabel: "AI Intelligence",
    description: "Ekstraksi statistik kata kunci penting dengan pembobotan RAKE/TF-IDF frekuensi dan ekspor CSV.",
    endpoint: "/api/ai/keywords",
    iconName: "Key",
    requiresKey: false,
  },
  {
    id: "language-detector",
    name: "Language Detector",
    category: "ai",
    categoryLabel: "AI Intelligence",
    description: "Deteksi otomatis bahasa teks dengan confidence score untuk lebih dari 50 bahasa dunia.",
    endpoint: "/api/ai/language",
    iconName: "Languages",
    requiresKey: false,
  },
  {
    id: "sentiment-analyzer",
    name: "Sentiment Analyzer",
    category: "ai",
    categoryLabel: "AI Intelligence",
    description: "Analisis polaritas sentimen (Positif, Netral, Negatif) beserta confidence score dan objektivitas.",
    endpoint: "/api/ai/sentiment",
    iconName: "Activity",
    requiresKey: false,
  },
  {
    id: "entity-extractor",
    name: "Entity Extractor (NER)",
    category: "ai",
    categoryLabel: "AI Intelligence",
    description: "Ekstraksi entitas publik dari teks: Organisasi, Lokasi Umum, Tanggal, Produk, Domain, dan Istilah Teknis.",
    endpoint: "/api/ai/entities",
    iconName: "Cpu",
    requiresKey: false,
  },
  {
    id: "ioc-extractor",
    name: "IOC Extractor (Threat Intel)",
    category: "ai",
    categoryLabel: "AI Intelligence",
    description: "Ekstraksi otomatis indikator ancaman siber (IP, Domain, MD5/SHA256, Email, CVE) dengan de-obfuscator.",
    endpoint: "/api/ai/ioc",
    iconName: "Bug",
    requiresKey: false,
    badge: "CYBERSEC",
  },

  // 28-34 File & Cryptographic Utilities
  {
    id: "image-metadata",
    name: "Image Metadata & EXIF Viewer",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Inspeksi metadata EXIF, kamera, resolusi. Koordinat GPS disembunyikan demi privasi pengguna.",
    endpoint: "/api/tools/image-metadata",
    iconName: "Camera",
    requiresKey: false,
  },
  {
    id: "video-metadata",
    name: "Video Metadata Viewer",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Analisis durasi, resolusi, format codec video/audio, bitrate, FPS, dan dimensi file.",
    endpoint: "/api/tools/video-metadata",
    iconName: "Video",
    requiresKey: false,
  },
  {
    id: "file-hash",
    name: "Cryptographic File Hash Generator",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Kalkulasi streaming hash kriptografi akurat: MD5, SHA-1, SHA-256, SHA-512 dengan fitur verifikasi hash.",
    endpoint: "/api/tools/hash",
    iconName: "Fingerprint",
    requiresKey: false,
    badge: "NATIVE",
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Optimasi ukuran gambar JPG, PNG, WebP dengan preview side-by-side dan perbandingan persentase hemat.",
    endpoint: "/api/tools/compress-image",
    iconName: "FileSpreadsheet",
    requiresKey: false,
  },
  {
    id: "video-compressor",
    name: "Video Compressor",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Konfigurasi resolusi dan bitrate video dengan status pemrosesan background job.",
    endpoint: "/api/tools/compress-video",
    iconName: "Sliders",
    requiresKey: false,
  },
  {
    id: "file-converter",
    name: "File Format Converter",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Konversi format file legal (JPG, PNG, WebP, MP3, WAV) dengan validasi MIME type ketat.",
    endpoint: "/api/tools/convert",
    iconName: "RefreshCw",
    requiresKey: false,
  },
  {
    id: "qr-analyzer",
    name: "QR Code Security Analyzer",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Dekode muatan QR code dan analisis URL mencurigakan tanpa membuka tautan secara otomatis.",
    endpoint: "/api/tools/qr-analyze",
    iconName: "QrCode",
    requiresKey: false,
  },

  // 35-36 Monitoring & Workspace Reporting
  {
    id: "rss-monitor",
    name: "RSS and News Monitor",
    category: "monitor",
    categoryLabel: "Monitoring",
    description: "Validasi feed RSS/Atom publik, filter kata kunci, riwayat pemindaian, dan notifikasi update.",
    endpoint: "/api/monitors",
    iconName: "Rss",
    requiresKey: false,
  },
  {
    id: "report-generator",
    name: "Investigation Report Generator",
    category: "workspace",
    categoryLabel: "Workspace",
    description: "Penyusun laporan intelijen profesional dengan cover, timeline, temuan, skor keyakinan, dan ekspor JSON/PDF.",
    endpoint: "/api/reports",
    iconName: "FileBadge",
    requiresKey: false,
    badge: "ENTERPRISE",
  },
  {
    id: "web-cloner",
    name: "Website Cloner & Source Archiver",
    category: "osint",
    categoryLabel: "Web Archiving",
    description: "Ekstrak kode sumber dan tampilan visual halaman web 100% utuh, inline stylesheet CSS & aset, live view sandbox, dan unduh sebagai file HTML mandiri dengan nama kustom.",
    endpoint: "/api/osint/web-cloner",
    iconName: "Globe",
    requiresKey: false,
    badge: "CLONER LIVE",
    requiredProviderName: "DOM Asset Resolver Engine",
  },
  // 38-52 New High-Impact OSINT & Converter Tools
  {
    id: "subdomain-finder",
    name: "Subdomain Finder via CT Logs",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Ekstraksi seluruh subdomain publik dan staging melalui Certificate Transparency (CT) Logs global tanpa brute-force bising.",
    endpoint: "/api/osint/subdomains",
    iconName: "Layers",
    requiresKey: false,
    badge: "CT-LOGS",
  },
  {
    id: "ssl-inspector",
    name: "SSL/TLS Certificate Deep Inspector",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Inspeksi sertifikat TLS socket langsung: SAN, Issuer CA, Cipher Suites, masa berlaku, dan SHA-256 fingerprint.",
    endpoint: "/api/osint/ssl-inspector",
    iconName: "ShieldCheck",
    requiresKey: false,
    badge: "RAW SOCKET",
  },
  {
    id: "security-headers",
    name: "Security Headers & CSP Auditor",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Audit mendalam header keamanan HTTP: HSTS, CSP, X-Frame-Options, Permissions-Policy dengan skor nilai Grade A+ s/d F.",
    endpoint: "/api/osint/security-headers",
    iconName: "ShieldAlert",
    requiresKey: false,
    badge: "SCORE CARD",
  },
  {
    id: "dns-propagation",
    name: "Global DNS Propagation Comparator",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Komparasi resolusi DNS record (A, AAAA, MX, NS) secara simultan di 8 resolver global (Google, Cloudflare, Quad9, OpenDNS, dll.).",
    endpoint: "/api/osint/dns-propagation",
    iconName: "Globe",
    requiresKey: false,
    badge: "8 NODES",
  },
  {
    id: "wayback-machine",
    name: "Wayback Machine Historical Explorer",
    category: "osint",
    categoryLabel: "Web Archiving",
    description: "Selidiki histori masa lalu situs web, snapshot halaman terhapus, dan timeline arsip Internet Archive Wayback Machine CDX API.",
    endpoint: "/api/osint/wayback",
    iconName: "Clock",
    requiresKey: false,
    badge: "CDX ARCHIVE",
  },
  {
    id: "robots-sitemap-analyzer",
    name: "Robots.txt & Sitemap Recon",
    category: "osint",
    categoryLabel: "Web Archiving",
    description: "Analisis direktif robots.txt dan sitemap.xml untuk mengungkap direktori rahasia, path admin, dan endpoint sensitif.",
    endpoint: "/api/osint/robots-sitemap",
    iconName: "FileSearch",
    requiresKey: false,
    badge: "PASSIVE RECON",
  },
  {
    id: "telegram-analyzer",
    name: "Telegram Channel Analyzer",
    category: "osint",
    categoryLabel: "Social OSINT",
    description: "Ekstraksi intelijen channel Telegram publik: subscriber, bio, status verified, dan feed broadcast terbaru tanpa perlu login.",
    endpoint: "/api/osint/telegram",
    iconName: "Send",
    requiresKey: false,
    badge: "TELEGRAM OSINT",
  },
  {
    id: "reddit-analyzer",
    name: "Reddit Profile & Subreddit OSINT",
    category: "osint",
    categoryLabel: "Social OSINT",
    description: "Analisis reputasi akun Reddit, breakdown karma, status verified email, dan informasi komunitas subreddit publik.",
    endpoint: "/api/osint/reddit",
    iconName: "MessageCircle",
    requiresKey: false,
    badge: "REDDIT API",
  },
  {
    id: "github-recon",
    name: "GitHub Developer & Repo Recon",
    category: "osint",
    categoryLabel: "Developer OSINT",
    description: "Pelacakan jejak digital developer: profil publik, repositori teratas, bahasa pemrograman favorit, dan aktivitas commit.",
    endpoint: "/api/osint/github",
    iconName: "GitBranch",
    requiresKey: false,
    badge: "DEV INTEL",
  },
  {
    id: "mac-lookup",
    name: "MAC Address & OUI Vendor Identifier",
    category: "files",
    categoryLabel: "Utility",
    description: "Identifikasi vendor produsen perangkat keras (Apple, Cisco, Intel, Samsung, IoT) dari alamat MAC standar IEEE OUI.",
    endpoint: "/api/tools/mac-lookup",
    iconName: "Cpu",
    requiresKey: false,
    badge: "IEEE OUI",
  },
  {
    id: "metadata-cleaner",
    name: "Metadata Privacy Scrubber (EXIF Cleaner)",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Hapus metadata sensitif gambar (koordinat GPS, model kamera, timestamp, serial) secara in-memory murni sebelum bukti dibagikan.",
    endpoint: "/api/tools/metadata-cleaner",
    iconName: "Camera",
    requiresKey: false,
    badge: "ZERO TRACE",
  },
  {
    id: "ioc-defang",
    name: "Threat Intel IOC Defang / Refang",
    category: "ai",
    categoryLabel: "AI Intelligence",
    description: "Sanitasi indikator ancaman siber berbahaya (URL, IP, Domain, Email) menjadi format aman CTI (hxxp, [.]) dan sebaliknya.",
    endpoint: "/api/tools/ioc-defang",
    iconName: "Bug",
    requiresKey: false,
    badge: "CTI TOOLS",
  },
  {
    id: "useragent-analyzer",
    name: "User-Agent & Bot Crawler Profiler",
    category: "osint",
    categoryLabel: "Forensics",
    description: "Inspeksi string User-Agent: engine peramban, OS, device, dan verifikasi legitimate bot (Googlebot, Bingbot, dll.).",
    endpoint: "/api/tools/useragent",
    iconName: "Compass",
    requiresKey: false,
    badge: "HEURISTIC",
  },
  {
    id: "forensic-decoder",
    name: "Multi-Format Forensic Decoder",
    category: "files",
    categoryLabel: "File Utilities",
    description: "Deteksi dan dekode otomatis payload forensik: Base64, Hex, URL-encoded, HTML entities, Rot13, Binary, dan JWT claims.",
    endpoint: "/api/tools/forensic-decode",
    iconName: "FileCode",
    requiresKey: false,
    badge: "MULTI DECODE",
  },
  {
    id: "redirect-tracer",
    name: "HTTP Redirect & Shortlink Tracer",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Lacak rantai pengalihan HTTP hop-by-hop (301, 302, 307, 308), status kode, header keamanan, dan URL target akhir.",
    endpoint: "/api/osint/redirect-tracer",
    iconName: "Milestone",
    requiresKey: false,
    badge: "HOP TRACER",
  },
  {
    id: "disposable-email-detector",
    name: "Disposable & Temp Mail Detector",
    category: "osint",
    categoryLabel: "Cyber Defense",
    description: "Deteksi instan apakah domain email merupakan temporary/burner email penyedia disposable atau institusi/perusahaan asli.",
    endpoint: "/api/osint/disposable-email",
    iconName: "MailWarning",
    requiresKey: false,
    badge: "MX AUDITOR",
  },
  {
    id: "asn-lookup",
    name: "ASN & BGP Route Explorer",
    category: "osint",
    categoryLabel: "Network OSINT",
    description: "Eksplorasi Autonomous System Number (ASN), nama ISP upstream, alokasi IP prefix BGP, dan negara hosting target.",
    endpoint: "/api/osint/asn",
    iconName: "Network",
    requiresKey: false,
    badge: "BGP ROUTE",
  },
  {
    id: "security-txt-checker",
    name: "RFC 9116 security.txt & Policy Inspector",
    category: "osint",
    categoryLabel: "Web Recon",
    description: "Inspeksi standar RFC 9116 security.txt pada domain untuk menemukan kontak keamanan siber, PGP key, dan program bug bounty.",
    endpoint: "/api/osint/security-txt",
    iconName: "FileCheck2",
    requiresKey: false,
    badge: "RFC 9116",
  },
  {
    id: "port-scanner",
    name: "Common Port & Service Inspector",
    category: "osint",
    categoryLabel: "Infrastructure",
    description: "Pemeriksaan status keterbukaan port jaringan umum (HTTP, HTTPS, SSH, FTP, SMTP, DNS, MySQL) secara non-intrusif.",
    endpoint: "/api/osint/port-scan",
    iconName: "RadioTower",
    requiresKey: false,
    badge: "SAFE PROBE",
  },
  {
    id: "cidr-calculator",
    name: "IP Subnet & CIDR Range Calculator",
    category: "files",
    categoryLabel: "Network Utility",
    description: "Kalkulasi matematis notasi subnetting CIDR: netmask, wildcard, usable IP range, total host, dan biner IP.",
    endpoint: "/api/tools/cidr",
    iconName: "Binary",
    requiresKey: false,
    badge: "IP MATH",
  },
  {
    id: "password-auditor",
    name: "Password Entropy & Brute-Force Auditor",
    category: "files",
    categoryLabel: "Security Utility",
    description: "Auditor matematis kekuatan password: nilai entropi Shannon (bits), estimasi waktu retak offline GPU cluster, dan deteksi pola.",
    endpoint: "/api/tools/password-audit",
    iconName: "KeyRound",
    requiresKey: false,
    badge: "ENTROPY AI",
  },
  {
    id: "ct-logs",
    name: "Certificate Transparency (CT) Logs Explorer",
    category: "osint",
    categoryLabel: "Web Recon",
    description: "Pencarian riwayat sertifikat SSL/TLS di log publik Certificate Transparency (crt.sh) untuk menyingkap subdomain rahasia.",
    endpoint: "/api/osint/ct-logs",
    iconName: "SearchCheck",
    requiresKey: false,
    badge: "CRT.SH INTEL",
  },
  {
    id: "email-breach-checker",
    name: "Email Breach & Compromise Auditor",
    category: "osint",
    categoryLabel: "Identity Intel",
    description: "Audit kompromi kebocoran data publik dan paste dump terhadap alamat email atau domain organisasi.",
    endpoint: "/api/osint/email-breach",
    iconName: "UserX",
    requiresKey: false,
    badge: "BREACH AUDIT",
  },
];
